FROM ubuntu:resolute-20260108@sha256:37a0633b900e99d0937986022b4b4018908e1361704425313cc1c348bebd7230

RUN apt-get update && apt-get install --no-install-recommends -y curl && \
    curl -sSfl https://get.anchore.io/syft | sh -s -- -b /usr/local/bin

CMD ["echo", "helo-world"]
